### ISSUE TITLE
Missing keycodes from Lua binding

### ISSUE THREAD

**Issue by carrotcreamsoup** [fordcars/SDL3D#4]
Not all keycodes are accessible from Lua. This is bad!
https://github.com/fordcars/SDL3D/blob/2618e73c2843cf239e4b336fad1ef4ee4149a3fc/src/Script.cpp#L396-L434

**Comment by philhzss** [comment]
I could fix this maybe!

**Comment by philhzss** [comment]
Do you mean that not all keys are registered in test.lua ??
![image](https://user-images.githubusercontent.com/41757256/101442878-2ccbf980-38ea-11eb-9e92-a3e67655e8e6.png)

Or you mean  that you want additional keys, like numbers, F keys etc to be added to Script.cpp?

**Comment by carrotcreamsoup** [comment]
Commit cae518758 fixes issue. Thanks PhilHzss!
